
[window]
decorations="full"
dynamic_title=true
opacity = 0.9
dynamic_padding=true
[window.padding]
y=5
x=5
[colors.primary]
background = "#000000"
foreground = "#ffffff"
[font] 
size = 10

[font.normal] 
family='Mononoki Nerd Font'
style="bold"
[font.bold]
family="Hack"
style="bold"

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c","export ZDOTDIR=$HOME/.config/zsh && zsh"]
